# https://taskfile.dev

version: "2"

tasks:
  release:
    cmds:
      - mkdir release || true
      - GOARCH=amd64 GOOS=windows go build -o release/spinme.exe
      - GOARCH=amd64 GOOS=linux go build -o release/spinme
      - GOARCH=amd64 GOOS=darwin go build -o release/spinme-darwin
    silent: true
