name: Continuous Integration Workflow
on: [push, pull_request]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v1
        with:
          go-version: "1.12.9"
      - run: curl -sL https://taskfile.dev/install.sh | sh
      - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.17.1
      - run: go fmt ./...
      - run: ./bin/golangci-lint run
      - run: go test -v -race ./...
      - run: ./bin/task release
