name: Continuous Integration Workflow
on: [push, pull_request]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v1
        with:
          go-version: "1.12.9"
      - run: go test -v ./...
